"use client";
import { useEffect, useState } from "react";
import { FileText, BookOpen, Lightbulb, CalendarDays, Target, MessageCircle } from "lucide-react";
import { ContactButton } from "@/components/SiteUI";

const tabs = [{ id: "grade69", label: "Grade 6–9" }, { id: "ol", label: "GCE O/L" }, { id: "al", label: "GCE A/L" }];
const juniorModes = [
  { icon: FileText, label: "PRACTISE", title: "Paper practice", text: "Attempt questions, review the answers and make mistakes useful.", steps: ["Choose a paper or a manageable question set.", "Work independently; use timed conditions for mock exams.", "Review answers with suitable marking guidance.", "Record weak topics and retry selected questions."] },
  { icon: BookOpen, label: "REVISIT", title: "Lesson recaps", text: "Return to school and tuition notes to check what your child understands.", steps: ["Identify the topic and review the relevant notes.", "Ask your child to explain the idea in their own words.", "Use a short exercise to check understanding.", "Set another revision target where needed."] },
  { icon: Lightbulb, label: "GET UNSTUCK", title: "Study assistance", text: "Give focused help where the guide has relevant subject knowledge.", steps: ["Let the student attempt the task first.", "Identify the specific point causing difficulty.", "Explain or work through a similar example.", "Record questions that need the subject teacher’s help."] },
];
const seniorModes = [
  { icon: CalendarDays, label: "ORGANISE", title: "Study planning", text: "Make a realistic plan around school, tuition, deadlines and revision.", steps: ["List the student’s subjects and upcoming tasks.", "Choose priorities together.", "Break large goals into manageable work blocks.", "Review the plan at the end of the visit."] },
  { icon: Target, label: "FOLLOW THROUGH", title: "Focused study blocks", text: "Support a consistent routine while the student owns the work.", steps: ["Agree on tasks and distraction boundaries.", "Use work blocks with scheduled breaks.", "Track what was attempted and completed.", "Adjust the workload rather than pushing through fatigue."] },
  { icon: MessageCircle, label: "REFLECT", title: "Accountability & review", text: "Turn completed work and unresolved doubts into a clear next step.", steps: ["Discuss what went well and what was difficult.", "Record unresolved subject questions.", "Choose the next revision target.", "Share a concise update with the parent."] },
];

export default function HowWeHelpTabs() {
  const [active, setActive] = useState("grade69");
  useEffect(() => { const sync = () => { const hash = window.location.hash.slice(1); if (tabs.some(tab => tab.id === hash)) setActive(hash); }; sync(); window.addEventListener("hashchange", sync); return () => window.removeEventListener("hashchange", sync); }, []);
  const select = (id: string, focus = false) => { setActive(id); window.history.replaceState(null, "", "#" + id); if (focus) document.getElementById("tab-" + id)?.focus(); };
  const current = tabs.find(tab => tab.id === active)!;
  return <div><div className="grade-tabs" role="tablist" aria-label="Student grade">{tabs.map((tab, i) => <button id={"tab-" + tab.id} key={tab.id} type="button" role="tab" aria-selected={active === tab.id} aria-controls="grade-support-panel" tabIndex={active === tab.id ? 0 : -1} onClick={() => select(tab.id)} onKeyDown={event => { let next; if (event.key === "ArrowRight") next = (i + 1) % tabs.length; if (event.key === "ArrowLeft") next = (i + tabs.length - 1) % tabs.length; if (event.key === "Home") next = 0; if (event.key === "End") next = tabs.length - 1; if (next !== undefined) { event.preventDefault(); select(tabs[next].id, true); } }}>{tab.label}</button>)}</div>
    <div id="grade-support-panel" role="tabpanel" aria-labelledby={"tab-" + active} tabIndex={0}><div className="mode-intro"><span className="small-label">{current.label.toUpperCase()} SUPPORT</span><h2>{active === "al" ? "A realistic plan. Consistent follow-through." : active === "ol" ? "Turn revision into exam practice." : "Build the habit, one task at a time."}</h2><p>{active === "al" ? "A/L visits focus on planning and accountability. Subject explanations depend on the guide’s expertise and should be agreed before booking." : "Choose the right mix of practice, recap and support for the work your child brings home."}</p></div><div className="mode-grid">{(active === "al" ? seniorModes : juniorModes).map(({ icon: Icon, label, title, text, steps }) => <article className="mode-card" key={title}><div className="icon-box"><Icon size={25} aria-hidden="true" /></div><span className="small-label">{label}</span><h3>{title}</h3><p>{text}</p><ol>{steps.map(step => <li key={step}>{step}</li>)}</ol></article>)}</div><div className="center-action"><ContactButton message={`Hi PathwayLK, I would like to discuss ${current.label} home study support, including subject availability and a suitable schedule.`}>Discuss {current.label} support</ContactButton></div></div></div>;
}
