import type { Metadata } from "next";
import Link from "next/link";
import { Check, GraduationCap, Users, ClipboardCheck } from "lucide-react";
import { Benefits, CTA, ContactButton, SampleReport, SectionHeading } from "@/components/SiteUI";

export const metadata: Metadata = { title: "Our service", description: "How PathwayLK supports revision, practice and independent study habits at home." };

export default function Service() {
  return <><div className="page-hero-band"><section className="container page-hero"><p className="eyebrow">YOUR CHILD STUDIES. WE SUPPORT THE ROUTINE.</p><h1>A real person.<br /><span className="highlight">A practical study plan.</span></h1><p>A Study Guide visits your home, works beside your child and helps turn school and tuition work into a manageable study routine. You get an update after each visit.</p><ContactButton /></section></div>
    <section className="container section section-topless"><Benefits /></section>
    <section className="tinted section"><div className="container two-column"><div><p className="eyebrow">WHAT A STUDY GUIDE DOES</p><h2>Your child does the work.<br />The guide helps them follow through.</h2><p className="section-intro">We help your child prepare a plan, work through their own tasks, review mistakes and decide what needs another attempt.</p><Link className="text-link" href="/our-service/how-we-help">Explore the session modes</Link><img className="service-photo" src="/study-visit.webp" alt="Illustrative Study Guide helping a student practise at home" width="1448" height="1086" loading="lazy" /><p className="center-note">Illustrative image</p></div><div className="scope-card"><h3>During a home visit</h3><ul className="plain-checks"><li><Check size={18} />Agree on realistic study targets.</li><li><Check size={18} />Use focused work blocks and planned breaks.</li><li><Check size={18} />Review questions within the guide’s expertise.</li><li><Check size={18} />Record unresolved doubts for the subject teacher.</li><li><Check size={18} />Discuss completed work and next steps with you.</li></ul><p className="scope-note">Subject support is agreed before booking. Visits complement school and tuition; outcomes depend on the student’s needs and participation.</p></div></div></section>
    <section className="container section"><SectionHeading eyebrow="A COMFORTABLE START" title="Know your guide. Know the plan.">Before inviting someone into your home, take time to discuss the match.</SectionHeading><div className="trust-grid">{[{ icon: GraduationCap, title: "Discuss subject expertise", text: "Ask about the guide’s studies, relevant subject experience, curriculum and language. Choose support that matches the subjects your child actually needs." }, { icon: Users, title: "Meet before committing", text: "Ask to speak with your proposed guide and discuss identity and reference verification. Your child should also feel comfortable with the match." }, { icon: ClipboardCheck, title: "Agree on the boundaries", text: "Choose a suitable shared study space, a parent or guardian contact, planned breaks and a clear way to raise concerns or request a different guide." }].map(({ icon: Icon, title, text }) => <article className="trust-item" key={title}><Icon size={26} aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="parent-updates" className="tinted section"><div className="container two-column report-section"><div><p className="eyebrow">AFTER THE SESSION</p><h2>From their notebook<br />to your parent update.</h2><p className="section-intro">Use a short discussion after each visit and a weekly review to follow the work, spot repeated difficulties and adjust the plan.</p><p>The sample shows the study goal, completed work, a tricky topic and the next action.</p></div><SampleReport /></div></section>
    <section className="container section"><SectionHeading eyebrow="GETTING STARTED" title="A few clear steps, together." /><ol className="journey-list">{[["Start with your child’s needs", "Send us the grade, subjects, language, location and preferred times."], ["Discuss a guide and schedule", "Confirm the guide match, the kind of support available and your planned visits."], ["Confirm the booking details", "Agree on price, session duration, breaks, parent discussion and cancellation arrangements."], ["Begin with realistic targets", "Use the first visit to understand the work and set an achievable study plan."], ["Review and adapt", "Discuss each visit and review the week to decide what to continue or adjust."]].map(([title, text], i) => <li key={title}><span className="journey-number">{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section><CTA /></>;
}
