import type { Metadata } from "next";
import { PlanCards, CTA, FAQ, ContactButton } from "@/components/SiteUI";

export const metadata: Metadata = { title: "Pricing & plans", description: "Compare PathwayLK weekly home study guidance plans, visits and session durations." };

export default function Pricing() {
  return <><div className="page-hero-band"><section className="container page-hero"><p className="eyebrow">HOME VISITS · WEEKLY PLANS</p><h1>Choose the visits.<br /><span className="highlight">Build the routine.</span></h1><p>Compare weekly home visit plans for Grade 6–9, O/L and A/L. Every plan includes one-to-one study support, a parent discussion and a weekly progress review.</p><div className="hero-checks centered"><span>No long-term contracts</span><span>One-to-one home visits</span><span>Parent updates</span></div></section></div>
    <section className="container section section-topless"><PlanCards /><div className="pricing-note"><strong>A note about extended A/L visits</strong><p>The advertised A/L package includes 24 scheduled hours a week. Discuss whether this fits around school, tuition and rest. Agree on breaks and the time included for parent discussion. A shorter schedule can be discussed before booking.</p></div><div className="intro-visit"><div><p className="eyebrow">START WITH A SMALLER STEP</p><h3>Start with a conversation. Then a visit.</h3><p>Ask about an introductory visit or fewer weekly sessions. Confirm the duration and price before booking.</p></div><ContactButton secondary message="Hi PathwayLK, can you tell me about an introductory home study visit, its price and guide availability?">Ask about a first visit</ContactButton></div><p className="center-note">Four-week totals assume all standard visits take place. Four weeks is not a calendar month.</p></section>
    <section className="tinted section"><div className="container two-column faq-section"><div><p className="eyebrow">PRICING QUESTIONS</p><h2>Know what you’re<br />booking.</h2><p className="section-intro">Confirm the details before paying, including any changes to the standard schedule.</p></div><FAQ pricing /></div></section><CTA /></>;
}
